language: python
python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8

env:
    - DJANGO='django>=4.0,<5.0'

install:
    - travis_retry pip install $DJANGO
    - travis_retry pip install -r requirements.txt

script:
    - python manage.py test

#branches:
#    only:
#        - master

